### ISSUE TITLE
Feature Request: exists() to detect whether a component was found on the DOM

### ISSUE THREAD

**Issue by dschinkel** [davidmfoley/isolate-components#9]
There are times we write tests for sad paths.

For React, returning `null` from a Component is a valid return value and actually is expected because it represents "Please don't render anything" for the DOM.

**Sad Path Scenario:**
**Given** there are no companies
**When** Featured Companies Loads
**Then** it shows no Featured Companies

Initial test I tried to write that implements that behavior:
```js
it.only('shows no featured companies when none found', async () => {
  const foundCompanies = null;

  const findFeaturedCompaniesStub = async () => foundCompanies;
  const featuredCompanies = isolateComponent(<FeaturedCompanies findFeaturedCompanies={findFeaturedCompaniesStub} />);
  await Promise.resolve();
  const presentableCompanies = featuredCompanies.findOne(PresentableFeaturedCompanies);

  expect(presentableCompanies).to.be.null
});
```

Right now, rather then providing some way to detect that the component wasn't found on the DOM/doesn't exist, it throws this error and my test fails (actually it doesn't finish running because this error is thrown instead):

```
Error: Could not find element matching function PresentableFeaturedCompanies({ companies }) {
    return (react_1.default.createElement("div", { className: "column-group margin-top-20" }, companies.map((company) => react_1.default.createElement(FeaturedCompanies, { companies: company, key: `company${company.name}` }))));
} 
```

Ideally, we should be able to check this in a clean way.  I wouldn't want to check for an error because the natural behavior is to expect nothing to be found

**So for example something like this would work really well if we could do that:**
```js
it.only('shows no featured companies when none found', async () => {
  const foundCompanies = null;
  const findFeaturedCompaniesStub = async () => foundCompanies;

  const featuredCompanies = isolateComponent(<FeaturedCompanies findFeaturedCompanies={findFeaturedCompaniesStub} />);
  await Promise.resolve();
  const presentableCompanies = featuredCompanies.findOne(PresentableFeaturedCompanies);

  expect(presentableCompanies.exists()).to.be.false
});
```

_We should be able to detect exists() on root **and** child nodes._

The resulting implementation that makes the test pass:
```js
return (
  featuredCompanies && (
    <div className="padding-bottom-20">
       <CompanyHeader />
       <PresentableFeaturedCompanies companies={featuredCompanies} />
    </div>
   ) || null
);
```

**Comment by davidmfoley** [comment]
Yeah this makes sense. Asserting that `findAll` returns an empty array (with chai: `expect(x.findAll(...)).to.eql([])`)  or has length 0 is a workaround.

Potential Changes:
We could make `findOne` return `null` in this case. (I don't like this idea)
We could add `exists` to return a boolean.
We could add other finders (`findFirst`?) that return null or a specific value that means `NotFound` if no match is found.
